### ISSUE TITLE
Machina-bridge crashes

### ISSUE THREAD

**Issue by jonathanleinola** [RobotExMachina/Machina-Bridge#8]
Machina-bridge crashes when trying to make a connection with virtual robot/controller. The error message is : could not LoadModuleFromControllerToTask, Could not load module Machina_ABB_Driver.mod from controller to task T_rob1, could not initialize streaming mode in the controller

**Comment by garciadelcastillo** [comment]
What are you trying to connect to?

**Comment by garciadelcastillo** [comment]
What are you trying to connect to? RobotStudio?

**Comment by jonathanleinola** [comment]
Yes, robot studio.

**Comment by jonathanleinola** [comment]
Right now i'm using the newest version of RobotStudio 2020. Might it be because of that? Also tried to run it with admin rights, still no luck :(

**Comment by garciadelcastillo** [comment]
Can you check if your robot is in automatic mode in RS?

**Comment by jonathanleinola** [comment]
Yes, it is in automatic mode and the motors are on

**Comment by garciadelcastillo** [comment]
Werid. I assume you have tried to restart everything right? :)

**Comment by garciadelcastillo** [comment]
Is your Bridge executable blocked by the system? And did you give it permission to communicate over the network?

**Comment by jonathanleinola** [comment]
Yup, i've tried to restarting the controller, restart everything (even computer) :D but still it crashes, when trying to do the connection. It injects all the .MOD files fine.

**Comment by jonathanleinola** [comment]
The bridge executable should have all rights;full control, modify, read & execute,write and i'm pretty sure that i gave it permission to communicate over the network

**Comment by jonathanleinola** [comment]
IRB_14050_0.5kg_0.5m (Station): 10052 - Regain start	17/11/2020 17.01.02	Event Log	
IRB_14050_0.5kg_0.5m (Station): 10053 - Regain ready	17/11/2020 17.01.02	Event Log	
IRB_14050_0.5kg_0.5m (Station): 10151 - Program started	17/11/2020 17.01.02	Event Log	

Actually afther this output from robot studio the Machina-Bridge crashes

**Comment by jonathanleinola** [comment]
and maybe this would be helpful too, i used the example_connectionCheck from Machina.NET package. 

ConnectionTest VERBOSE: Scanning the network for controllers...
ConnectionTest VERBOSE: Found controller IRB_910INV_3kg_0.35m on IRB_910INV_3kg_0.35m
ConnectionTest DEBUG:
ConnectionTest DEBUG: Loaded IP 127.0.0.1
ConnectionTest DEBUG: Logged on as Default User user
ConnectionTest DEBUG: RobotWare IRB_910INV_3kg_0.35m
ConnectionTest DEBUG: RobotWareVersion 7.0.0.4
ConnectionTest DEBUG: hasMultiTasking? False
ConnectionTest DEBUG: hasEGM? False
ConnectionTest DEBUG: Mastership test OK
ConnectionTest DEBUG: Retrieved task T_ROB1
ConnectionTest DEBUG: OPERATING MODE CHANGED: Auto
ConnectionTest DEBUG: CONTROLLER STATECHANGED: MotorsOn
ConnectionTest DEBUG: EXECUTION STATUS CHANGED: Running
ConnectionTest DEBUG: Loaded ABB Driver module and cofigured to 127.0.0.1:7000
ConnectionTest DEBUG: Saved module to C:\Users\jonat\AppData\Local\Temp\Machina_ABB_Driver.mod
ConnectionTest DEBUG: Copied Machina_ABB_Driver.mod to Machina
ConnectionTest VERBOSE: Deleting module Machina_Driver from T_ROB1
ConnectionTest DEBUG: CLEAR MODULES ERROR: ABB.Robotics.GenericControllerException:  Operation is illegal in current execution state. ---> RobotStudio.Services.RobApi.RobApiException: C0049007 : Operation is illegal in current execution state.
ERROR: c:\buildagents\agent-seabb-is-13900.1\_work\4\s\areas\robapi\components\robdomainhooks\rdh_rapid.cpp[7021]: org_code: -4503 new_code: 0xc0049007;
Url:/RAPID/T_ROB1  Cmd:SET  Prop:DeleteModule  Args:-Name "Machina_Driver"  Elapsed:0  CurrentCmds:0
   --- End of inner exception stack trace ---
   at Adapters.Task.DeleteModule(String module)
   at ABB.Robotics.Controllers.Internal.RapidModule.Delete()
   at ABB.Robotics.Controllers.RapidDomain.Module.Delete()
   at Machina.Drivers.Communication.RobotStudioManager.ClearAllModules(Task task) in C:\Users\~\Machina.NET\src\Machina\Drivers\Communication\RobotStudioManager.cs:line 531
ConnectionTest DEBUG: Cleared 0 modules from main task
ConnectionTest DEBUG: RAPID MASTERSHIP STATUS CHANGED: Remote
ConnectionTest ERROR: Could not LoadModuleFromControllerToTask
ConnectionTest DEBUG: ABB.Robotics.GenericControllerException:  Operation is illegal in current execution state. ---> RobotStudio.Services.RobApi.RobApiException: C0049007 : Operation is illegal in current execution state.
LoadModuleFile
ERROR: c:\buildagents\agent-seabb-is-13900.1\_work\4\s\areas\robapi\components\robdomainhooks\rdh_rapid.cpp[6979]: org_code: -4503 new_code: 0xc0049007;
   --- End of inner exception stack trace ---
   at Adapters.Task.RobLoadModule(String path, RobRapidLoadMode mode)
   at ABB.Robotics.Controllers.Internal.RapidTask.LoadModule(String path, RapidLoadMode mode)
   at ABB.Robotics.Controllers.RapidDomain.Task.LoadModuleFromFile(String filePath, RapidLoadMode mode)
   at Machina.Drivers.Communication.RobotStudioManager.LoadModuleFromControllerToTask(Task task, String filename, Boolean wipeout) in C:\Users\~\git\Machina.NET\src\Machina\Drivers\Communication\RobotStudioManager.cs:line 998
ConnectionTest ERROR: Could not load module Machina_ABB_Driver.mod from controller to task T_ROB1
ConnectionTest DEBUG: Could not upload Driver module
ConnectionTest ERROR: Could not initialize Streaming Mode in the controller
ConnectionTest ERROR: Cannot connect to device

**Comment by garciadelcastillo** [comment]
Looks like your robot might be stuck on the wrong state? Can you try creating a new robot station?

**Comment by jonathanleinola** [comment]
Still nothing :( I can control it manually through flexpendant

**Comment by garciadelcastillo** [comment]
I have no idea what might be going on. I find it strange that you can control it with the flexpendant while in automatic mode though... I think there is something not working with your robot state, and it doesn't let Machina initialize the driver.

**Comment by jonathanleinola** [comment]
Oh, it's not working in automatic mode but in manual mode with the flexpendant. Sorry for misleading. I managed to operate it remotely with open_abb library. What do you mean by robot state?
